version: '3'
services:
  web:
    container_name: flask-app
    restart: always
    build: ./app
    volumes:
      - ./app:/usr/src/app
    ports:
      - "5000:5000"
    command: gunicorn -w 1 -b :5000 views:app

  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web