apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: gcr.io/udacity-game-catalog/flask:v1
          command: ["gunicorn","-w","1","-b",":5000","views:app"]
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: flask-app