apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: gcr.io/udacity-game-catalog/nginx:v1
          imagePullPolicy: Always
          ports:
            - name: nginx-443
              containerPort: 443
            - name: nginx-80
              containerPort: 80